# Generated by Django 4.2.4 on 2023-09-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='list_update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
