# Generated by Django 4.2.4 on 2023-09-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_request_taking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='returning_date',
            field=models.DateField(default=0.0009000900090009),
            preserve_default=False,
        ),
    ]
